//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
)

func main() {
	f, err := os.Create("config_gen.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Fprintf(w, "%s", `// Code generated by genconfig.go; DO NOT EDIT

package ript

/* Copyright © 2022 Brian C Sparks <briancsparks@gmail.com> -- MIT (see LICENSE file) */

`)

	fmt.Fprintf(w, "var myDirname string = \"%s\"\n", cwd)

	w.Flush()
}
